// ─────────────────────────────────────────────────────────────────────────────
// VegFru — Product Catalog  (100+ products, real Unsplash images)
// ─────────────────────────────────────────────────────────────────────────────

export const categories = [
  { id: 'all',        label: 'All',        emoji: '🌿' },
  { id: 'vegetables', label: 'Vegetables', emoji: '🥦' },
  { id: 'fruits',     label: 'Fruits',     emoji: '🍎' },
  { id: 'leafy',      label: 'Leafy',      emoji: '🥬' },
  { id: 'herbs',      label: 'Herbs',      emoji: '🌱' },
  { id: 'berries',    label: 'Berries',    emoji: '🍓' },
  { id: 'citrus',     label: 'Citrus',     emoji: '🍋' },
  { id: 'exotic',     label: 'Exotic',     emoji: '🥭' },
  { id: 'seasonal',   label: 'Seasonal',   emoji: '🍂' },
  { id: 'root',       label: 'Root Veg',   emoji: '🥕' },
]

export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice: number
  unit: string
  emoji: string
  image: string
  bg: string
  accent: string
  badge: string | null
  badgeColor: string
  description: string
  longDescription: string
  rating: number
  reviews: number
  tag: string
  nutritionHighlight: string
  origin: string
  stock: number
  keywords: string[]
}

export const products: Product[] = [
  // ── VEGETABLES (25) ─────────────────────────────────────────────────────────
  {
    id: 1, name: 'Cherry Tomatoes', category: 'vegetables', price: 49, originalPrice: 65, unit: '500g',
    emoji: '🍅', image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80',
    bg: 'from-red-100 to-orange-50', accent: '#ef4444', badge: 'BESTSELLER', badgeColor: 'bg-red-500',
    description: 'Vine-ripened, bursting with sweetness',
    longDescription: 'Handpicked every morning. Vine-ripened until perfectly sweet with deep umami flavour. Perfect for salads, pasta, and roasting whole.',
    rating: 4.9, reviews: 1243, tag: 'Organic', nutritionHighlight: 'Lycopene & Vitamin C', origin: 'Nashik, Maharashtra', stock: 50,
    keywords: ['tomato', 'cherry tomato', 'salad', 'red', 'vine', 'pasta'],
  },
  {
    id: 2, name: 'Heirloom Tomatoes', category: 'vegetables', price: 89, originalPrice: 120, unit: '500g',
    emoji: '🍅', image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&q=80',
    bg: 'from-orange-100 to-yellow-50', accent: '#f97316', badge: 'GOURMET', badgeColor: 'bg-orange-500',
    description: 'Multi-coloured heirloom varieties, chef's favourite',
    longDescription: 'Purple, yellow, and striped heirloom tomatoes from heritage seeds. Each variety brings a unique smoky-sweet to tangy flavour profile prized by chefs.',
    rating: 4.9, reviews: 387, tag: 'Heirloom', nutritionHighlight: 'Antioxidants & Flavonoids', origin: 'Ooty, Tamil Nadu', stock: 15,
    keywords: ['heirloom tomato', 'colorful', 'gourmet', 'chef', 'purple', 'yellow'],
  },
  {
    id: 3, name: 'Red Tomatoes', category: 'vegetables', price: 35, originalPrice: 48, unit: '1 kg',
    emoji: '🍅', image: 'https://images.unsplash.com/photo-1558818498-28c1e002b655?w=600&q=80',
    bg: 'from-red-50 to-rose-50', accent: '#dc2626', badge: null, badgeColor: '',
    description: 'Farm-fresh red tomatoes, perfect for cooking',
    longDescription: 'Classic red tomatoes with a perfect balance of sweetness and acidity. Ideal for curries, sauces, and salads. Sourced daily from local farmers.',
    rating: 4.7, reviews: 892, tag: 'Local', nutritionHighlight: 'Vitamin A & C', origin: 'Pune, Maharashtra', stock: 100,
    keywords: ['tomato', 'red tomato', 'cooking', 'curry', 'sauce', 'sabzi'],
  },
  {
    id: 4, name: 'White Cauliflower', category: 'vegetables', price: 49, originalPrice: 65, unit: '1 head',
    emoji: '🥦', image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&q=80',
    bg: 'from-gray-50 to-slate-50', accent: '#6b7280', badge: null, badgeColor: '',
    description: 'Farm-fresh cauliflower with tight curds',
    longDescription: 'Dense, tight-curd white cauliflower sourced from hill farms. Ideal for roasting, making rice, or classic Indian gobi curry.',
    rating: 4.6, reviews: 467, tag: 'Fresh', nutritionHighlight: 'Vitamin C & Choline', origin: 'Srinagar, J&K', stock: 55,
    keywords: ['cauliflower', 'gobi', 'curry', 'roast', 'white', 'sabzi'],
  },
  {
    id: 5, name: 'Purple Broccoli', category: 'vegetables', price: 89, originalPrice: 110, unit: '400g',
    emoji: '🥦', image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=600&q=80',
    bg: 'from-purple-100 to-violet-50', accent: '#8b5cf6', badge: 'RARE', badgeColor: 'bg-purple-500',
    description: 'Anthocyanin-rich heirloom broccoli',
    longDescription: 'Purple sprouting broccoli — sweeter than regular with a tender stem. The colour indicates powerful anthocyanin antioxidants.',
    rating: 4.8, reviews: 145, tag: 'Heirloom', nutritionHighlight: 'Anthocyanins & Sulforaphane', origin: 'Kodaikanal, Tamil Nadu', stock: 15,
    keywords: ['broccoli', 'purple', 'heirloom', 'rare', 'antioxidant', 'gourmet'],
  },
  {
    id: 6, name: 'Red Bell Pepper', category: 'vegetables', price: 79, originalPrice: 100, unit: '2 pcs',
    emoji: '🌶️', image: 'https://images.unsplash.com/photo-1526346698789-22fd84314424?w=600&q=80',
    bg: 'from-red-100 to-orange-50', accent: '#ef4444', badge: null, badgeColor: '',
    description: 'Sweet, thick-walled red capsicum',
    longDescription: 'Mature red bell peppers with thick, sweet walls — 3× more Vitamin C than green peppers. Perfect for stir-fry, roasting, and stuffing.',
    rating: 4.7, reviews: 534, tag: 'Fresh', nutritionHighlight: 'Vitamin C >200% DV', origin: 'Himachal Pradesh', stock: 50,
    keywords: ['bell pepper', 'capsicum', 'red pepper', 'sweet', 'stir fry', 'roast'],
  },
  {
    id: 7, name: 'Green Chillies', category: 'vegetables', price: 25, originalPrice: 35, unit: '100g',
    emoji: '🌶️', image: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#16a34a', badge: null, badgeColor: '',
    description: 'Fresh green chillies — heart of Indian cooking',
    longDescription: 'Fiery fresh green chillies from Andhra Pradesh. Essential for authentic Indian cooking, chutneys, and pickles.',
    rating: 4.8, reviews: 1056, tag: 'Local', nutritionHighlight: 'Capsaicin & Vitamin C', origin: 'Andhra Pradesh', stock: 100,
    keywords: ['chilli', 'green chilli', 'spicy', 'hot', 'indian', 'mirchi', 'andhra'],
  },
  {
    id: 8, name: 'Kashmiri Red Chilli', category: 'vegetables', price: 45, originalPrice: 60, unit: '50g',
    emoji: '🌶️', image: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#dc2626', badge: 'PREMIUM', badgeColor: 'bg-red-600',
    description: 'Brilliant colour, mild heat — the cook\'s secret',
    longDescription: 'Famous Kashmiri red chillies known for vibrant deep red colour and mild heat. The secret behind rich red restaurant curries.',
    rating: 4.9, reviews: 289, tag: 'Premium', nutritionHighlight: 'Capsaicin & Vitamin A', origin: 'Kashmir', stock: 40,
    keywords: ['kashmiri chilli', 'red', 'mild', 'colour', 'curry', 'spice', 'masala'],
  },
  {
    id: 9, name: 'White Onion', category: 'vegetables', price: 35, originalPrice: 48, unit: '1 kg',
    emoji: '🧅', image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=600&q=80',
    bg: 'from-gray-50 to-purple-50', accent: '#9333ea', badge: null, badgeColor: '',
    description: 'Crisp white onions — milder & sweeter than red',
    longDescription: 'White onions with milder, sweeter flavour. Perfect raw in salsas or cooked in cream sauces. Farm-fresh from Nashik.',
    rating: 4.7, reviews: 689, tag: 'Local', nutritionHighlight: 'Quercetin & Prebiotic Fibre', origin: 'Nashik, Maharashtra', stock: 150,
    keywords: ['onion', 'white onion', 'pyaz', 'mild', 'sweet', 'salsa', 'cooking'],
  },
  {
    id: 10, name: 'Purple Garlic', category: 'vegetables', price: 59, originalPrice: 80, unit: '100g',
    emoji: '🧄', image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=600&q=80',
    bg: 'from-purple-50 to-pink-50', accent: '#a855f7', badge: 'AROMATIC', badgeColor: 'bg-purple-500',
    description: 'Pungent purple garlic with intense flavour',
    longDescription: 'Hardneck purple garlic with a more complex, robust flavour. Each clove is larger, easier to peel, and packed with allicin.',
    rating: 4.9, reviews: 512, tag: 'Organic', nutritionHighlight: 'Allicin & Manganese', origin: 'Himachal Pradesh', stock: 55,
    keywords: ['garlic', 'purple garlic', 'lasun', 'aromatic', 'allicin', 'health', 'cooking'],
  },
  {
    id: 11, name: 'Zucchini', category: 'vegetables', price: 59, originalPrice: 80, unit: '500g',
    emoji: '🥒', image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=600&q=80',
    bg: 'from-lime-100 to-green-50', accent: '#84cc16', badge: null, badgeColor: '',
    description: 'Tender green zucchini — great for stir-fry & pasta',
    longDescription: 'Young green zucchini harvested while tender for best texture. Make zoodles for low-carb eating or grill as a healthy side.',
    rating: 4.6, reviews: 256, tag: 'Fresh', nutritionHighlight: 'Vitamin C & Potassium', origin: 'Himachal Pradesh', stock: 40,
    keywords: ['zucchini', 'courgette', 'green', 'low carb', 'stir fry', 'noodles', 'pasta'],
  },
  {
    id: 12, name: 'Cucumber', category: 'vegetables', price: 29, originalPrice: 38, unit: '500g',
    emoji: '🥒', image: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=600&q=80',
    bg: 'from-green-50 to-teal-50', accent: '#0d9488', badge: null, badgeColor: '',
    description: 'Cool, crunchy cucumbers — straight from the vine',
    longDescription: 'Freshly harvested cucumbers with crisp texture. 96% water — perfect for hydration, raita, and salads.',
    rating: 4.7, reviews: 789, tag: 'Local', nutritionHighlight: 'Hydration & B-Vitamins', origin: 'Maharashtra', stock: 100,
    keywords: ['cucumber', 'kheera', 'cool', 'salad', 'raita', 'hydrating', 'green'],
  },
  {
    id: 13, name: 'Pumpkin', category: 'vegetables', price: 39, originalPrice: 52, unit: '500g',
    emoji: '🎃', image: 'https://images.unsplash.com/photo-1572883454114-1cf0031ede2a?w=600&q=80',
    bg: 'from-orange-100 to-amber-50', accent: '#f97316', badge: 'AUTUMN', badgeColor: 'bg-orange-500',
    description: 'Sweet orange pumpkin — perfect for soups & curries',
    longDescription: 'Vibrant orange pumpkin with dense, sweet flesh. Perfect for roasting, soups, curries, and pies. Seeds are a nutritious snack.',
    rating: 4.7, reviews: 389, tag: 'Seasonal', nutritionHighlight: 'Beta-carotene & Zinc', origin: 'Rajasthan', stock: 55,
    keywords: ['pumpkin', 'kaddu', 'orange', 'soup', 'curry', 'roast', 'sweet'],
  },
  {
    id: 14, name: 'Green Cabbage', category: 'vegetables', price: 29, originalPrice: 40, unit: '1 head',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#65a30d', badge: null, badgeColor: '',
    description: 'Firm, crunchy cabbage — great for stir-fry',
    longDescription: 'Compact green cabbage with crisp, tightly packed leaves. Perfect for coleslaw, stir-fry, soups, and stuffed cabbage rolls.',
    rating: 4.5, reviews: 489, tag: 'Local', nutritionHighlight: 'Vitamin K & Glucosinolates', origin: 'Ooty, Tamil Nadu', stock: 70,
    keywords: ['cabbage', 'patta gobhi', 'stir fry', 'coleslaw', 'green', 'slaw'],
  },
  {
    id: 15, name: 'Bitter Gourd', category: 'vegetables', price: 39, originalPrice: 52, unit: '250g',
    emoji: '🥒', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#65a30d', badge: 'MEDICINAL', badgeColor: 'bg-green-700',
    description: 'Karela — blood sugar\'s natural regulator',
    longDescription: 'Fresh bitter gourd (karela) — a proven Ayurvedic remedy for blood sugar regulation. Excellent stuffed, stir-fried, or juiced with apple.',
    rating: 4.5, reviews: 378, tag: 'Medicinal', nutritionHighlight: 'Charantin & Vitamin C', origin: 'Maharashtra', stock: 55,
    keywords: ['bitter gourd', 'karela', 'bitter', 'blood sugar', 'medicinal', 'ayurvedic'],
  },
  {
    id: 16, name: 'Purple Brinjal', category: 'vegetables', price: 35, originalPrice: 48, unit: '500g',
    emoji: '🍆', image: 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&q=80',
    bg: 'from-purple-100 to-violet-50', accent: '#7c3aed', badge: null, badgeColor: '',
    description: 'Glossy brinjal — versatile for bharta & moussaka',
    longDescription: 'Firm, glossy purple brinjal perfect for bharta, baingan masala, moussaka, and ratatouille. Sourced from Andhra Pradesh.',
    rating: 4.7, reviews: 434, tag: 'Local', nutritionHighlight: 'Nasunin & Fibre', origin: 'Andhra Pradesh', stock: 70,
    keywords: ['brinjal', 'eggplant', 'aubergine', 'baingan', 'purple', 'bharta'],
  },
  {
    id: 17, name: 'Bhindi (Okra)', category: 'vegetables', price: 39, originalPrice: 52, unit: '250g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#65a30d', badge: null, badgeColor: '',
    description: 'Tender young okra — essential for Indian cooking',
    longDescription: 'Young, tender bhindi (lady\'s finger) pods. Essential for South Indian sambar and stir-fry. Cook on high heat for crisp results.',
    rating: 4.7, reviews: 545, tag: 'Local', nutritionHighlight: 'Folate & Vitamin K', origin: 'Andhra Pradesh', stock: 80,
    keywords: ['bhindi', 'okra', 'ladyfinger', 'indian', 'sambar', 'stir fry'],
  },
  {
    id: 18, name: 'Button Mushrooms', category: 'vegetables', price: 79, originalPrice: 105, unit: '250g',
    emoji: '🍄', image: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=600&q=80',
    bg: 'from-gray-100 to-stone-50', accent: '#78716c', badge: 'UMAMI', badgeColor: 'bg-stone-500',
    description: 'Fresh white button mushrooms — earthy & versatile',
    longDescription: 'Cultivated fresh white button mushrooms with firm, meaty texture. Perfect for risotto, pasta, soups, and sautéing with garlic butter.',
    rating: 4.8, reviews: 612, tag: 'Cultivated', nutritionHighlight: 'Vitamin D & B-Vitamins', origin: 'Himachal Pradesh', stock: 55,
    keywords: ['mushroom', 'button', 'fungi', 'risotto', 'pasta', 'earthy', 'umami'],
  },
  {
    id: 19, name: 'Sweet Corn', category: 'vegetables', price: 39, originalPrice: 52, unit: '2 pcs',
    emoji: '🌽', image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&q=80',
    bg: 'from-yellow-100 to-amber-50', accent: '#eab308', badge: null, badgeColor: '',
    description: 'Fresh sweet corn — tender, juicy kernels',
    longDescription: 'Super-sweet fresh corn cobs. Sugars convert to starch after harvest, so eat same day. Boil, grill, or roast. Kids\' favourite.',
    rating: 4.8, reviews: 889, tag: 'Seasonal', nutritionHighlight: 'Lutein & Vitamin B1', origin: 'Punjab', stock: 60,
    keywords: ['corn', 'sweet corn', 'maize', 'bbq', 'boil', 'yellow', 'grilled'],
  },
  {
    id: 20, name: 'Green Peas', category: 'vegetables', price: 55, originalPrice: 72, unit: '500g',
    emoji: '🫛', image: 'https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#4ade80', badge: 'SEASONAL', badgeColor: 'bg-green-500',
    description: 'Fresh shelled green peas — sweet & protein-rich',
    longDescription: 'Freshly shelled green peas with natural sweetness. Perfect for matar paneer, pulao, pasta, and simply blanched with butter.',
    rating: 4.9, reviews: 567, tag: 'Seasonal', nutritionHighlight: 'Plant Protein & Fibre', origin: 'Punjab', stock: 45,
    keywords: ['peas', 'matar', 'green peas', 'seasonal', 'winter', 'sweet', 'protein'],
  },
  {
    id: 21, name: 'Brussels Sprouts', category: 'vegetables', price: 89, originalPrice: 120, unit: '250g',
    emoji: '🥦', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#16a34a', badge: 'WINTER', badgeColor: 'bg-green-600',
    description: 'Mini cabbages — nutty when roasted to perfection',
    longDescription: 'Best when halved and roasted at high heat until caramelised and crispy. Toss with olive oil, honey, and sea salt. Converts even die-hard haters.',
    rating: 4.6, reviews: 223, tag: 'Winter', nutritionHighlight: 'Vitamin K & Sulforaphane', origin: 'Himachal Pradesh', stock: 30,
    keywords: ['brussels sprouts', 'mini cabbage', 'roast', 'winter', 'nutty', 'healthy'],
  },
  {
    id: 22, name: 'Asparagus', category: 'vegetables', price: 149, originalPrice: 199, unit: '200g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1537486336219-d07b3b98b014?w=600&q=80',
    bg: 'from-green-100 to-emerald-50', accent: '#10b981', badge: 'GOURMET', badgeColor: 'bg-emerald-500',
    description: 'Tender asparagus spears — a spring gourmet treat',
    longDescription: 'Thin, tender asparagus spears — a spring luxury. Blanch lightly, grill, or roast with olive oil and sea salt. Perfect with eggs.',
    rating: 4.9, reviews: 189, tag: 'Gourmet', nutritionHighlight: 'Folate & Prebiotic Fibre', origin: 'Himachal Pradesh', stock: 15,
    keywords: ['asparagus', 'spring', 'gourmet', 'tender', 'green', 'luxury', 'fancy'],
  },
  {
    id: 23, name: 'Drumstick (Moringa)', category: 'vegetables', price: 45, originalPrice: 60, unit: '250g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1537486336219-d07b3b98b014?w=600&q=80',
    bg: 'from-green-100 to-teal-50', accent: '#0f766e', badge: 'SUPERFOOD', badgeColor: 'bg-teal-600',
    description: 'Moringa drumstick — nutritional powerhouse',
    longDescription: 'Fresh moringa drumsticks — more calcium than milk, more iron than spinach. Essential for South Indian sambar and Kerala curries.',
    rating: 4.8, reviews: 434, tag: 'Organic', nutritionHighlight: 'Calcium, Iron & Protein', origin: 'Tamil Nadu', stock: 55,
    keywords: ['drumstick', 'moringa', 'murungakkai', 'superfood', 'sambar', 'south indian'],
  },
  {
    id: 24, name: 'Bottle Gourd', category: 'vegetables', price: 29, originalPrice: 40, unit: '1 pc',
    emoji: '🥒', image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#65a30d', badge: null, badgeColor: '',
    description: 'Light, digestible lauki — ideal summer vegetable',
    longDescription: 'Smooth, pale green bottle gourd (lauki/dudhi) — 96% water. Perfect for lauki ki sabzi, kofte, halwa, and raita. Very cooling in summer.',
    rating: 4.6, reviews: 334, tag: 'Local', nutritionHighlight: 'Vitamin B & Choline', origin: 'Maharashtra', stock: 70,
    keywords: ['bottle gourd', 'lauki', 'dudhi', 'cooling', 'digestive', 'summer', 'light'],
  },
  {
    id: 25, name: 'Shallots', category: 'vegetables', price: 59, originalPrice: 80, unit: '250g',
    emoji: '🧅', image: 'https://images.unsplash.com/photo-1603052875302-d376b7c0a2d1?w=600&q=80',
    bg: 'from-purple-50 to-pink-50', accent: '#a855f7', badge: 'GOURMET', badgeColor: 'bg-purple-500',
    description: 'Sweet, mild shallots — the chef\'s onion',
    longDescription: 'Small, elongated shallots with a milder, sweeter flavour than regular onions. Preferred by professional chefs for delicate sauces and vinaigrettes.',
    rating: 4.8, reviews: 189, tag: 'Gourmet', nutritionHighlight: 'Quercetin & Allicin', origin: 'Tamil Nadu', stock: 55,
    keywords: ['shallots', 'small onion', 'chef', 'mild', 'sweet', 'gourmet', 'french'],
  },

  // ── FRUITS (20) ─────────────────────────────────────────────────────────────
  {
    id: 26, name: 'Alphonso Mangoes', category: 'fruits', price: 299, originalPrice: 380, unit: '1 kg',
    emoji: '🥭', image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80',
    bg: 'from-yellow-100 to-amber-50', accent: '#f59e0b', badge: 'SEASONAL', badgeColor: 'bg-amber-500',
    description: 'The king of mangoes — straight from Ratnagiri',
    longDescription: 'Authentic GI-tagged Ratnagiri Alphonso mangoes — fibreless, saffron-hued flesh with an intensely rich tropical fragrance. Available for just 6 weeks a year.',
    rating: 5.0, reviews: 2891, tag: 'Premium', nutritionHighlight: 'Vitamin C, A & Fibre', origin: 'Ratnagiri, Maharashtra', stock: 30,
    keywords: ['mango', 'alphonso', 'hapus', 'king', 'ratnagiri', 'tropical', 'seasonal', 'aamras'],
  },
  {
    id: 27, name: 'Kesar Mangoes', category: 'fruits', price: 249, originalPrice: 320, unit: '1 kg',
    emoji: '🥭', image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80',
    bg: 'from-orange-100 to-yellow-50', accent: '#ea580c', badge: 'SEASONAL', badgeColor: 'bg-orange-500',
    description: 'Saffron-coloured Kesar mangoes from Junagadh',
    longDescription: 'Junagadh\'s prized Kesar mangoes — named for their saffron colour and aroma. Less fibrous with a rich sweet flavour. Perfect for aamras and milkshakes.',
    rating: 4.9, reviews: 1256, tag: 'Premium', nutritionHighlight: 'Beta-carotene & Vitamin C', origin: 'Junagadh, Gujarat', stock: 25,
    keywords: ['kesar', 'mango', 'saffron', 'gujarat', 'aamras', 'milkshake', 'seasonal'],
  },
  {
    id: 28, name: 'Himachali Apple', category: 'fruits', price: 149, originalPrice: 195, unit: '1 kg',
    emoji: '🍎', image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#dc2626', badge: 'PREMIUM', badgeColor: 'bg-red-600',
    description: 'Crisp Royal Gala apples from Himachal orchards',
    longDescription: 'Crisp Royal Gala apples from the apple orchards of Shimla — sweet, juicy, slightly tart. No wax coating, delivered within 48 hours of harvest.',
    rating: 4.8, reviews: 1056, tag: 'Local', nutritionHighlight: 'Quercetin & Pectin Fibre', origin: 'Shimla, HP', stock: 55,
    keywords: ['apple', 'himachali', 'royal gala', 'red', 'crisp', 'sweet', 'shimla'],
  },
  {
    id: 29, name: 'Cavendish Banana', category: 'fruits', price: 45, originalPrice: 60, unit: '1 dozen',
    emoji: '🍌', image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&q=80',
    bg: 'from-yellow-100 to-amber-50', accent: '#f59e0b', badge: 'POPULAR', badgeColor: 'bg-yellow-500',
    description: 'Ripe yellow bananas — energy on the go',
    longDescription: 'Classic Cavendish bananas ripened to perfect yellow. A complete portable snack with potassium for muscle function. Great for smoothies and baking.',
    rating: 4.8, reviews: 1678, tag: 'Local', nutritionHighlight: 'Potassium & Vitamin B6', origin: 'Tamil Nadu', stock: 100,
    keywords: ['banana', 'kela', 'yellow', 'energy', 'potassium', 'smoothie', 'ripe'],
  },
  {
    id: 30, name: 'Pomegranate', category: 'fruits', price: 89, originalPrice: 120, unit: '1 pc',
    emoji: '🍎', image: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#e11d48', badge: 'ANTIOXIDANT', badgeColor: 'bg-rose-600',
    description: 'Ruby-red pomegranate bursting with arils',
    longDescription: 'Plump pomegranates with glistening ruby arils. Rich in punicalagins — antioxidants unique to pomegranates. Great for juicing or garnishing dishes.',
    rating: 4.8, reviews: 734, tag: 'Local', nutritionHighlight: 'Punicalagins & Vitamin C', origin: 'Solapur, Maharashtra', stock: 40,
    keywords: ['pomegranate', 'anaar', 'ruby', 'arils', 'antioxidant', 'juice', 'red'],
  },
  {
    id: 31, name: 'Black Seedless Grapes', category: 'fruits', price: 99, originalPrice: 130, unit: '500g',
    emoji: '🍇', image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&q=80',
    bg: 'from-purple-100 to-violet-50', accent: '#7c3aed', badge: 'POPULAR', badgeColor: 'bg-purple-600',
    description: 'Sweet black seedless grapes — farm direct',
    longDescription: 'Plump, seedless black grapes with intensely sweet flesh and thin skin. Perfect for snacking, cheese boards, and making homemade wine.',
    rating: 4.8, reviews: 845, tag: 'Local', nutritionHighlight: 'Resveratrol & Antioxidants', origin: 'Nashik, Maharashtra', stock: 55,
    keywords: ['grapes', 'black grape', 'seedless', 'sweet', 'snack', 'fruit', 'nashik'],
  },
  {
    id: 32, name: 'Watermelon', category: 'fruits', price: 49, originalPrice: 65, unit: '1 kg cut',
    emoji: '🍉', image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=600&q=80',
    bg: 'from-red-100 to-pink-50', accent: '#f43f5e', badge: 'SUMMER', badgeColor: 'bg-red-500',
    description: 'Chilled watermelon — summer in a fruit',
    longDescription: 'Crisp, ruby-red watermelon slices, chilled and ready to eat. Over 90% water makes it the ultimate hydrating summer fruit.',
    rating: 4.8, reviews: 1056, tag: 'Seasonal', nutritionHighlight: 'Lycopene & Citrulline', origin: 'Andhra Pradesh', stock: 80,
    keywords: ['watermelon', 'tarbooj', 'red', 'summer', 'hydrating', 'slice', 'sweet'],
  },
  {
    id: 33, name: 'Guava', category: 'fruits', price: 49, originalPrice: 65, unit: '500g',
    emoji: '🍐', image: 'https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#22c55e', badge: null, badgeColor: '',
    description: 'Sweet, aromatic guavas — 4× Vitamin C of oranges',
    longDescription: 'Pink-fleshed guavas with intoxicating fragrance and exceptional sweetness. Contains 4× more Vitamin C than oranges. Perfect with chaat masala.',
    rating: 4.7, reviews: 589, tag: 'Local', nutritionHighlight: 'Vitamin C (228mg/100g)', origin: 'Allahabad, UP', stock: 65,
    keywords: ['guava', 'amrood', 'pink', 'vitamin C', 'sweet', 'aromatic', 'pink flesh'],
  },
  {
    id: 34, name: 'Pineapple', category: 'fruits', price: 89, originalPrice: 120, unit: '1 pc',
    emoji: '🍍', image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80',
    bg: 'from-yellow-100 to-amber-50', accent: '#ca8a04', badge: null, badgeColor: '',
    description: 'Sweet, juicy Kew pineapple — tropical perfection',
    longDescription: 'Golden Kew variety pineapple from Kerala\'s coastal farms. Exceptionally sweet, juicy, aromatic with minimal bitterness.',
    rating: 4.8, reviews: 634, tag: 'Local', nutritionHighlight: 'Bromelain & Vitamin C', origin: 'Kerala', stock: 30,
    keywords: ['pineapple', 'ananas', 'tropical', 'sweet', 'juicy', 'bromelain', 'kerala'],
  },
  {
    id: 35, name: 'Papaya', category: 'fruits', price: 69, originalPrice: 90, unit: '1 pc',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=600&q=80',
    bg: 'from-orange-100 to-yellow-50', accent: '#f97316', badge: null, badgeColor: '',
    description: 'Sun-ripened papaya with brilliant orange flesh',
    longDescription: 'Sweet, buttery papaya with vibrant orange flesh and digestive enzyme papain. Eat ripe as a tropical treat or use raw for Thai salads.',
    rating: 4.6, reviews: 401, tag: 'Local', nutritionHighlight: 'Papain, Vitamin C & A', origin: 'Karnataka', stock: 40,
    keywords: ['papaya', 'papita', 'orange', 'tropical', 'digestive', 'enzyme', 'thai'],
  },
  {
    id: 36, name: 'Lychee', category: 'fruits', price: 149, originalPrice: 199, unit: '250g',
    emoji: '🍇', image: 'https://images.unsplash.com/photo-1596591868231-05e808fd7b79?w=600&q=80',
    bg: 'from-pink-100 to-rose-50', accent: '#fb7185', badge: 'SEASONAL', badgeColor: 'bg-pink-500',
    description: 'Fragrant summer lychees — available briefly',
    longDescription: 'Fragrant Muzaffarpur lychees with intensely sweet, floral flesh reminiscent of roses. Available for only 4 weeks. The jewel of summer fruits.',
    rating: 5.0, reviews: 812, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Oligonol', origin: 'Bihar / West Bengal', stock: 20,
    keywords: ['lychee', 'litchi', 'pink', 'seasonal', 'sweet', 'floral', 'summer', 'bihar'],
  },
  {
    id: 37, name: 'Muskmelon', category: 'fruits', price: 59, originalPrice: 78, unit: '1 pc',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1571575173700-afb9492437e9?w=600&q=80',
    bg: 'from-yellow-100 to-orange-50', accent: '#d97706', badge: null, badgeColor: '',
    description: 'Fragrant muskmelon with honey-sweet orange flesh',
    longDescription: 'Fragrant muskmelon (cantaloupe) with netted orange skin and honey-sweet orange flesh. Eat chilled with lime for the ultimate summer dessert.',
    rating: 4.7, reviews: 378, tag: 'Seasonal', nutritionHighlight: 'Vitamin A & Potassium', origin: 'Rajasthan', stock: 40,
    keywords: ['muskmelon', 'cantaloupe', 'orange', 'sweet', 'fragrant', 'summer', 'melon'],
  },
  {
    id: 38, name: 'Coconut', category: 'fruits', price: 45, originalPrice: 60, unit: '1 pc',
    emoji: '🥥', image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&q=80',
    bg: 'from-amber-50 to-yellow-50', accent: '#92400e', badge: null, badgeColor: '',
    description: 'Fresh tender coconut — naturally hydrating',
    longDescription: 'Fresh green or brown coconuts from Kerala\'s coastal farms. Full of electrolyte-rich water, perfect for post-workout hydration. The soft meat is a tropical delight.',
    rating: 4.7, reviews: 489, tag: 'Local', nutritionHighlight: 'Electrolytes & MCTs', origin: 'Kerala', stock: 55,
    keywords: ['coconut', 'nariyal', 'tender', 'water', 'hydration', 'tropical', 'kerala'],
  },
  {
    id: 39, name: 'Honeydew Melon', category: 'fruits', price: 149, originalPrice: 185, unit: '1 pc',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1571575173700-afb9492437e9?w=600&q=80',
    bg: 'from-emerald-100 to-teal-50', accent: '#10b981', badge: null, badgeColor: '',
    description: 'Crisp and sweet honeydew — summer perfection',
    longDescription: 'Pale green honeydew melon with crisp, sweet green flesh — the most delicate of all melons. Pairs beautifully with prosciutto or vanilla ice cream.',
    rating: 4.7, reviews: 303, tag: 'Fresh', nutritionHighlight: 'Vitamin B6 & Potassium', origin: 'Rajasthan', stock: 25,
    keywords: ['honeydew', 'melon', 'green', 'sweet', 'summer', 'crisp', 'cool'],
  },
  {
    id: 40, name: 'Yellow Peach', category: 'fruits', price: 149, originalPrice: 199, unit: '500g',
    emoji: '🍑', image: 'https://images.unsplash.com/photo-1595743825637-cdafc8ad4173?w=600&q=80',
    bg: 'from-orange-100 to-pink-50', accent: '#f97316', badge: 'SEASONAL', badgeColor: 'bg-orange-500',
    description: 'Velvety, fragrant peaches from Himalayan orchards',
    longDescription: 'Tree-ripened yellow peaches from Himachal Pradesh\'s mountain orchards. Velvet skin, juicy golden flesh, and an intoxicating aroma. Limited season.',
    rating: 4.9, reviews: 334, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Carotenoids', origin: 'Himachal Pradesh', stock: 20,
    keywords: ['peach', 'fruit', 'seasonal', 'velvet', 'summer', 'juicy', 'himalayan'],
  },
  {
    id: 41, name: 'Plum', category: 'fruits', price: 129, originalPrice: 170, unit: '500g',
    emoji: '🍑', image: 'https://images.unsplash.com/photo-1597714026720-8f74c62310ba?w=600&q=80',
    bg: 'from-purple-100 to-red-50', accent: '#9333ea', badge: 'SEASONAL', badgeColor: 'bg-purple-500',
    description: 'Sweet-tart red plums from Himachal orchards',
    longDescription: 'Juicy red-purple plums with tart skin and sweet flesh. Rich in sorbitol which promotes digestive health. Excellent for jams, crumbles, and chutneys.',
    rating: 4.8, reviews: 267, tag: 'Seasonal', nutritionHighlight: 'Vitamin K & Sorbitol', origin: 'Himachal Pradesh', stock: 25,
    keywords: ['plum', 'aalubukhara', 'purple', 'seasonal', 'tart', 'sweet', 'jam'],
  },
  {
    id: 42, name: 'Custard Apple', category: 'fruits', price: 89, originalPrice: 120, unit: '2 pcs',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#65a30d', badge: 'SEASONAL', badgeColor: 'bg-green-600',
    description: 'Sweet, creamy sharifa — the ice cream of fruits',
    longDescription: 'Custard apple (sharifa/sitaphal) with bumpy green exterior and creamy white flesh naturally sweet as vanilla ice cream. Available only in autumn.',
    rating: 4.8, reviews: 256, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & B6', origin: 'Maharashtra', stock: 25,
    keywords: ['custard apple', 'sharifa', 'sitaphal', 'sweet', 'creamy', 'seasonal', 'autumn'],
  },
  {
    id: 43, name: 'Kiwi Fruit', category: 'fruits', price: 199, originalPrice: 260, unit: '4 pcs',
    emoji: '🥝', image: 'https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#84cc16', badge: 'IMPORTED', badgeColor: 'bg-lime-600',
    description: 'Tangy green kiwi from New Zealand',
    longDescription: 'Plump Hayward kiwis from New Zealand — more Vitamin C than an orange and more potassium than a banana. Perfect for breakfast and pavlova.',
    rating: 4.8, reviews: 467, tag: 'Imported', nutritionHighlight: 'Vitamin C & Actinidain', origin: 'New Zealand', stock: 30,
    keywords: ['kiwi', 'kiwifruit', 'new zealand', 'green', 'vitamin C', 'tangy', 'imported'],
  },
  {
    id: 44, name: 'Pear (Naspati)', category: 'fruits', price: 129, originalPrice: 169, unit: '500g',
    emoji: '🍐', image: 'https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=600&q=80',
    bg: 'from-yellow-100 to-green-50', accent: '#84cc16', badge: null, badgeColor: '',
    description: 'Buttery, sweet Bartlett pears from Kashmir',
    longDescription: 'Golden-green Bartlett pears from Kashmir valleys. When perfectly ripe, the flesh is buttery, sweet, and intensely juicy.',
    rating: 4.7, reviews: 289, tag: 'Seasonal', nutritionHighlight: 'Fibre & Vitamin K', origin: 'Kashmir', stock: 30,
    keywords: ['pear', 'naspati', 'yellow', 'sweet', 'buttery', 'kashmir', 'juicy'],
  },
  {
    id: 45, name: 'Cherries', category: 'fruits', price: 299, originalPrice: 380, unit: '250g',
    emoji: '🍒', image: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#dc2626', badge: 'SEASONAL', badgeColor: 'bg-red-600',
    description: 'Sweet Himachali cherries — briefly available',
    longDescription: 'Deep red sweet cherries from Kinnaur\'s high-altitude orchards. Available for only 4–6 weeks each year. Rich in melatonin — a natural sleep aid.',
    rating: 5.0, reviews: 378, tag: 'Seasonal', nutritionHighlight: 'Melatonin & Anthocyanins', origin: 'Kinnaur, HP', stock: 12,
    keywords: ['cherry', 'cherries', 'red', 'seasonal', 'sweet', 'himachal', 'kinnaur'],
  },

  // ── LEAFY GREENS (8) ────────────────────────────────────────────────────────
  {
    id: 46, name: 'Baby Spinach', category: 'leafy', price: 39, originalPrice: 55, unit: '250g',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80',
    bg: 'from-green-100 to-emerald-50', accent: '#22c55e', badge: null, badgeColor: '',
    description: 'Tender leaves, rich in iron & vitamins',
    longDescription: 'Young baby spinach leaves harvested at peak tenderness. Perfect for salads, smoothies, and sautéing. Never treated with pesticides. Dewy fresh.',
    rating: 4.7, reviews: 956, tag: 'Organic', nutritionHighlight: 'Iron, Folate & Vitamin K', origin: 'Bengaluru, Karnataka', stock: 80,
    keywords: ['spinach', 'baby spinach', 'leafy green', 'iron', 'salad', 'healthy', 'palak'],
  },
  {
    id: 47, name: 'Iceberg Lettuce', category: 'leafy', price: 45, originalPrice: 60, unit: '1 head',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600&q=80',
    bg: 'from-lime-50 to-green-50', accent: '#84cc16', badge: 'FRESH', badgeColor: 'bg-lime-500',
    description: 'Crisp, fresh lettuce for salads & wraps',
    longDescription: 'Cool and crispy iceberg lettuce with tight, fresh heads. Perfect for burgers, wraps, and classic salads. Delivers that satisfying crunch.',
    rating: 4.6, reviews: 503, tag: 'Local', nutritionHighlight: 'Hydrating & Low-calorie', origin: 'Nashik, Maharashtra', stock: 60,
    keywords: ['lettuce', 'iceberg', 'salad', 'crunch', 'wrap', 'burger', 'green'],
  },
  {
    id: 48, name: 'Curly Kale', category: 'leafy', price: 59, originalPrice: 80, unit: '200g',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=600&q=80',
    bg: 'from-emerald-100 to-green-50', accent: '#10b981', badge: 'SUPERFOOD', badgeColor: 'bg-emerald-600',
    description: 'Nutrient-dense superfood, freshly harvested',
    longDescription: 'Dark, curly kale packed with more nutrients per calorie than almost any other food. Massage with olive oil for salads or blend into smoothies.',
    rating: 4.8, reviews: 334, tag: 'Organic', nutritionHighlight: 'Vitamins A, C, K & Calcium', origin: 'Dehradun, Uttarakhand', stock: 40,
    keywords: ['kale', 'superfood', 'healthy', 'smoothie', 'green', 'nutrient', 'detox'],
  },
  {
    id: 49, name: 'Baby Arugula', category: 'leafy', price: 69, originalPrice: 90, unit: '100g',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-teal-50 to-green-50', accent: '#0d9488', badge: null, badgeColor: '',
    description: 'Peppery arugula with a distinctive bold flavour',
    longDescription: 'Wild rocket arugula with that signature peppery bite. Pairs beautifully with parmesan, prosciutto, and lemon. A gourmet staple in Italian cuisine.',
    rating: 4.7, reviews: 189, tag: 'Gourmet', nutritionHighlight: 'Glucosinolates & Vitamin K', origin: 'Ooty, Tamil Nadu', stock: 30,
    keywords: ['arugula', 'rocket', 'peppery', 'italian', 'gourmet', 'salad', 'wild'],
  },
  {
    id: 50, name: 'Bok Choy', category: 'leafy', price: 59, originalPrice: 80, unit: '300g',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#65a30d', badge: null, badgeColor: '',
    description: 'Chinese cabbage with crisp stalks & tender leaves',
    longDescription: 'Baby bok choy with thick, crisp white stalks and tender dark green leaves. Stir-fry quickly in sesame oil and garlic for an authentic Asian side.',
    rating: 4.7, reviews: 223, tag: 'Imported', nutritionHighlight: 'Vitamin A & Calcium', origin: 'China / India', stock: 35,
    keywords: ['bok choy', 'chinese cabbage', 'asian', 'stir fry', 'ramen', 'soup'],
  },
  {
    id: 51, name: 'Fenugreek Leaves', category: 'leafy', price: 25, originalPrice: 35, unit: '100g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#16a34a', badge: null, badgeColor: '',
    description: 'Fresh methi — slightly bitter, extremely nutritious',
    longDescription: 'Fresh fenugreek leaves (methi) with a slightly bitter flavour that beautifully balances rich curries. Essential for methi dal, aloo methi, and parathas.',
    rating: 4.8, reviews: 634, tag: 'Local', nutritionHighlight: 'Iron, Zinc & Protein', origin: 'Rajasthan', stock: 90,
    keywords: ['methi', 'fenugreek', 'leaves', 'bitter', 'dal', 'aloo methi', 'paratha'],
  },
  {
    id: 52, name: 'Amaranth Leaves', category: 'leafy', price: 25, originalPrice: 35, unit: '200g',
    emoji: '🥬', image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80',
    bg: 'from-red-50 to-pink-50', accent: '#f43f5e', badge: null, badgeColor: '',
    description: 'Chaulai — iron-rich red-green leafy green',
    longDescription: 'Vibrant amaranth leaves (chaulai/rajgira) with red and green hues. Extremely nutritious and delicious sautéed with garlic. A staple in Indian home cooking.',
    rating: 4.7, reviews: 289, tag: 'Local', nutritionHighlight: 'Iron & Protein (plant-based)', origin: 'UP / Bihar', stock: 70,
    keywords: ['amaranth', 'chaulai', 'rajgira', 'red leafy', 'iron', 'nutrition', 'saag'],
  },
  {
    id: 53, name: 'Watercress', category: 'leafy', price: 89, originalPrice: 120, unit: '100g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-green-50 to-teal-50', accent: '#0d9488', badge: 'SUPERFOOD', badgeColor: 'bg-teal-600',
    description: 'Peppery watercress — CDC #1 most nutrient-dense food',
    longDescription: 'Fresh watercress ranked #1 most nutrient-dense food by the CDC. Excellent raw in salads, sandwiches, or briefly wilted as a side. Pairs beautifully with steak.',
    rating: 4.8, reviews: 156, tag: 'Organic', nutritionHighlight: 'Vitamin K >200% DV', origin: 'Hill stations', stock: 15,
    keywords: ['watercress', 'peppery', 'superfood', 'nutrient dense', 'salad', 'steak'],
  },

  // ── HERBS (10) ──────────────────────────────────────────────────────────────
  {
    id: 54, name: 'Fresh Basil', category: 'herbs', price: 29, originalPrice: 40, unit: '50g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&q=80',
    bg: 'from-lime-100 to-green-50', accent: '#84cc16', badge: null, badgeColor: '',
    description: 'Aromatic Italian basil, freshly harvested',
    longDescription: 'Lush, fragrant Italian sweet basil with glossy leaves. Freshly harvested and delivered within hours. Perfect for pesto, Caprese salad, pasta, and pizza.',
    rating: 4.6, reviews: 378, tag: 'Organic', nutritionHighlight: 'Vitamin K & Eugenol', origin: 'Bengaluru, Karnataka', stock: 60,
    keywords: ['basil', 'herb', 'italian', 'pesto', 'pizza', 'fragrant', 'pasta', 'caprese'],
  },
  {
    id: 55, name: 'Fresh Mint', category: 'herbs', price: 25, originalPrice: 35, unit: '50g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&q=80',
    bg: 'from-teal-50 to-green-50', accent: '#0d9488', badge: null, badgeColor: '',
    description: 'Cool, refreshing mint for drinks & cooking',
    longDescription: 'Vibrantly fresh spearmint with intense cooling aroma. Perfect for mojitos, mint chutney, raita, teas, and desserts. Harvested the same morning.',
    rating: 4.7, reviews: 545, tag: 'Organic', nutritionHighlight: 'Menthol & Vitamin A', origin: 'Uttar Pradesh', stock: 55,
    keywords: ['mint', 'pudina', 'herb', 'mojito', 'chutney', 'cool', 'raita', 'tea'],
  },
  {
    id: 56, name: 'Coriander (Dhania)', category: 'herbs', price: 15, originalPrice: 22, unit: '100g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#16a34a', badge: 'POPULAR', badgeColor: 'bg-green-600',
    description: 'Fresh coriander — essential for Indian cooking',
    longDescription: 'Intensely aromatic fresh coriander (dhania) with bright green leaves. Indispensable in Indian, Mexican, and Middle Eastern cuisines.',
    rating: 4.8, reviews: 1567, tag: 'Local', nutritionHighlight: 'Vitamin C & Quercetin', origin: 'Rajasthan', stock: 120,
    keywords: ['coriander', 'cilantro', 'dhania', 'herb', 'indian', 'garnish', 'chutney'],
  },
  {
    id: 57, name: 'Fresh Rosemary', category: 'herbs', price: 45, originalPrice: 60, unit: '30g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80',
    bg: 'from-blue-50 to-indigo-50', accent: '#4f46e5', badge: null, badgeColor: '',
    description: 'Woody, aromatic rosemary — Mediterranean staple',
    longDescription: 'Fragrant sprigs of fresh rosemary with pine-like aroma. Essential for roasts, focaccia, potatoes, and marinades. Pairs perfectly with garlic.',
    rating: 4.8, reviews: 267, tag: 'Gourmet', nutritionHighlight: 'Rosmarinic Acid & Iron', origin: 'Ooty, Tamil Nadu', stock: 35,
    keywords: ['rosemary', 'herb', 'mediterranean', 'roast', 'aromatic', 'gourmet', 'focaccia'],
  },
  {
    id: 58, name: 'Fresh Thyme', category: 'herbs', price: 40, originalPrice: 55, unit: '30g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1600231915116-8d9e7749d05e?w=600&q=80',
    bg: 'from-green-50 to-teal-50', accent: '#0f766e', badge: null, badgeColor: '',
    description: 'Earthy French thyme with tiny, fragrant leaves',
    longDescription: 'Delicate sprigs of fresh thyme with earthy, lemony flavour. A foundational herb for French cuisine — bouquet garni, soups, chicken, and roasted vegetables.',
    rating: 4.7, reviews: 154, tag: 'Gourmet', nutritionHighlight: 'Thymol & Vitamin C', origin: 'Kodaikanal, TN', stock: 30,
    keywords: ['thyme', 'herb', 'french', 'aromatic', 'chicken', 'soup', 'earthy'],
  },
  {
    id: 59, name: 'Flat Leaf Parsley', category: 'herbs', price: 25, originalPrice: 35, unit: '50g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1597916829826-02e5bb4a54e0?w=600&q=80',
    bg: 'from-lime-50 to-green-50', accent: '#4ade80', badge: null, badgeColor: '',
    description: 'Bright, fresh parsley — great for garnish & cooking',
    longDescription: 'Italian flat-leaf parsley with a clean, bright flavour. Use in tabbouleh, chimichurri, pasta, and as garnish. A kitchen essential.',
    rating: 4.6, reviews: 289, tag: 'Organic', nutritionHighlight: 'Vitamin K & Apigenin', origin: 'Bengaluru, Karnataka', stock: 45,
    keywords: ['parsley', 'herb', 'italian', 'garnish', 'tabbouleh', 'fresh', 'chimichurri'],
  },
  {
    id: 60, name: 'Lemongrass', category: 'herbs', price: 35, originalPrice: 48, unit: '100g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&q=80',
    bg: 'from-yellow-50 to-green-50', accent: '#ca8a04', badge: null, badgeColor: '',
    description: 'Aromatic lemongrass for Thai curries & teas',
    longDescription: 'Fresh lemongrass stalks with intense citrusy, floral aroma. Essential for Thai green curry, tom kha, lemongrass tea, and Vietnamese pho.',
    rating: 4.8, reviews: 178, tag: 'Gourmet', nutritionHighlight: 'Citral & Antioxidants', origin: 'Kerala', stock: 40,
    keywords: ['lemongrass', 'thai', 'aromatic', 'curry', 'tea', 'citrus', 'pho'],
  },
  {
    id: 61, name: 'Microgreens Mix', category: 'herbs', price: 149, originalPrice: 199, unit: '100g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#84cc16', badge: 'GOURMET', badgeColor: 'bg-lime-500',
    description: 'Chef-grade microgreens — 40× the nutrients',
    longDescription: 'A vibrant mix of micro sunflower, radish, pea shoots, and basil. 4–40× more nutrients than mature vegetables. Grown hydroponically. Used in Michelin-starred restaurants.',
    rating: 4.9, reviews: 189, tag: 'Gourmet', nutritionHighlight: 'Concentrated vitamins & polyphenols', origin: 'Bengaluru, Karnataka', stock: 20,
    keywords: ['microgreens', 'micro greens', 'gourmet', 'chef', 'seedlings', 'garnish', 'hydroponic'],
  },
  {
    id: 62, name: 'Curry Leaves', category: 'herbs', price: 15, originalPrice: 22, unit: '50g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#16a34a', badge: null, badgeColor: '',
    description: 'Fresh curry leaves — soul of South Indian cooking',
    longDescription: 'Fragrant fresh curry leaves (kadi patta) — the defining aroma of South Indian tempering (tadka). Essential for sambar, rasam, chutneys, and coconut curries.',
    rating: 4.9, reviews: 789, tag: 'Local', nutritionHighlight: 'Carbazole Alkaloids & Iron', origin: 'Tamil Nadu / Karnataka', stock: 100,
    keywords: ['curry leaves', 'kadi patta', 'south indian', 'tadka', 'tempering', 'sambar', 'aromatic'],
  },
  {
    id: 63, name: 'Dill Leaves', category: 'herbs', price: 25, originalPrice: 35, unit: '50g',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#84cc16', badge: null, badgeColor: '',
    description: 'Feathery dill — perfect for fish, eggs & pickling',
    longDescription: 'Fresh dill with feathery leaves and anise-like flavour. Essential for dill pickles, salmon, tzatziki, and Scandinavian cuisine. Also used in Indian shepu dal.',
    rating: 4.7, reviews: 134, tag: 'Gourmet', nutritionHighlight: 'Flavonoids & Vitamin A', origin: 'Maharashtra', stock: 35,
    keywords: ['dill', 'suwa', 'shepu', 'herb', 'pickle', 'fish', 'feathery', 'anise'],
  },

  // ── BERRIES (6) ─────────────────────────────────────────────────────────────
  {
    id: 64, name: 'Strawberries', category: 'berries', price: 129, originalPrice: 160, unit: '250g',
    emoji: '🍓', image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&q=80',
    bg: 'from-rose-100 to-pink-50', accent: '#f43f5e', badge: 'FRESH', badgeColor: 'bg-rose-500',
    description: 'Sweet Mahabaleshwar strawberries — picked daily',
    longDescription: 'Plump, juicy strawberries from the cool hills of Mahabaleshwar. Harvested at peak ripeness every morning and delivered chilled. Perfect for smoothies and desserts.',
    rating: 4.9, reviews: 1412, tag: 'Local', nutritionHighlight: 'Vitamin C & Ellagic Acid', origin: 'Mahabaleshwar, MH', stock: 45,
    keywords: ['strawberry', 'berry', 'red', 'smoothie', 'dessert', 'fresh', 'sweet', 'mahabaleshwar'],
  },
  {
    id: 65, name: 'Blueberries', category: 'berries', price: 249, originalPrice: 320, unit: '125g',
    emoji: '🫐', image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&q=80',
    bg: 'from-blue-100 to-indigo-50', accent: '#6366f1', badge: 'IMPORTED', badgeColor: 'bg-indigo-500',
    description: 'Plump blueberries bursting with antioxidants',
    longDescription: 'Fresh imported blueberries — plump, sweet, and loaded with anthocyanins. One of the most nutrient-dense foods. Great for smoothies, pancakes, yoghurt.',
    rating: 4.8, reviews: 789, tag: 'Imported', nutritionHighlight: 'Anthocyanins & Vitamin C', origin: 'Peru / Chile', stock: 20,
    keywords: ['blueberry', 'blue', 'berry', 'antioxidant', 'superfood', 'imported', 'smoothie'],
  },
  {
    id: 66, name: 'Raspberries', category: 'berries', price: 299, originalPrice: 380, unit: '125g',
    emoji: '🍓', image: 'https://images.unsplash.com/photo-1506459225024-1428097a7e18?w=600&q=80',
    bg: 'from-rose-100 to-red-50', accent: '#e11d48', badge: 'IMPORTED', badgeColor: 'bg-rose-600',
    description: 'Tart, fragrant raspberries — perfect for desserts',
    longDescription: 'Delicate, intensely flavoured raspberries with beautiful tartness. Freshly imported and delivered cold. Perfect for pavlovas, cheesecakes, jams.',
    rating: 4.9, reviews: 334, tag: 'Imported', nutritionHighlight: 'Ellagic Acid & Fibre', origin: 'Europe', stock: 15,
    keywords: ['raspberry', 'berry', 'tart', 'dessert', 'imported', 'pavlova', 'jam'],
  },
  {
    id: 67, name: 'Blackberries', category: 'berries', price: 279, originalPrice: 360, unit: '125g',
    emoji: '🫐', image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80',
    bg: 'from-purple-100 to-indigo-50', accent: '#7c3aed', badge: 'EXOTIC', badgeColor: 'bg-purple-600',
    description: 'Sweet-tart blackberries with deep rich flavour',
    longDescription: 'Juicy, deep-purple blackberries with complex sweet-tart flavour. Rich in fibre and antioxidants. Excellent in jams, crumbles, smoothies.',
    rating: 4.8, reviews: 178, tag: 'Imported', nutritionHighlight: 'Vitamin C, K & Manganese', origin: 'UK / Australia', stock: 12,
    keywords: ['blackberry', 'berry', 'dark', 'purple', 'jam', 'imported', 'crumble'],
  },
  {
    id: 68, name: 'Amla (Gooseberry)', category: 'berries', price: 49, originalPrice: 65, unit: '250g',
    emoji: '🍇', image: 'https://images.unsplash.com/photo-1597063168589-f5a5f0fb47c0?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#84cc16', badge: 'SUPERFOOD', badgeColor: 'bg-lime-600',
    description: 'Indian gooseberry — 20× Vitamin C of oranges',
    longDescription: 'Fresh amla (Indian gooseberry) — one of the most potent natural sources of Vitamin C on earth. Perfect for pickles, murabba, amla juice, and hair care.',
    rating: 4.8, reviews: 534, tag: 'Superfood', nutritionHighlight: 'Vitamin C (600mg/100g)', origin: 'UP / Rajasthan', stock: 45,
    keywords: ['amla', 'gooseberry', 'vitamin C', 'superfood', 'immunity', 'hair', 'tart'],
  },
  {
    id: 69, name: 'Passion Fruit', category: 'berries', price: 179, originalPrice: 230, unit: '6 pcs',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1604495772376-9657f0035f01?w=600&q=80',
    bg: 'from-purple-100 to-yellow-50', accent: '#9333ea', badge: 'EXOTIC', badgeColor: 'bg-purple-500',
    description: 'Wrinkled purple passion fruit — intensely tropical',
    longDescription: 'Purple passion fruits — wrinkled skin means perfectly ripe! Cut in half to reveal golden jelly-like seeds. Intensely tart tropical flavour. Perfect in cocktails and cheesecake.',
    rating: 4.9, reviews: 189, tag: 'Imported', nutritionHighlight: 'Vitamin A, C & Piceatannol', origin: 'Sri Lanka / India', stock: 18,
    keywords: ['passion fruit', 'purple', 'tropical', 'tart', 'exotic', 'cocktail', 'cheesecake'],
  },

  // ── CITRUS (6) ──────────────────────────────────────────────────────────────
  {
    id: 70, name: 'Meyer Lemons', category: 'citrus', price: 69, originalPrice: 90, unit: '500g',
    emoji: '🍋', image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80',
    bg: 'from-yellow-100 to-lime-50', accent: '#eab308', badge: 'GOURMET', badgeColor: 'bg-yellow-500',
    description: 'Sweeter, thinner-skinned Meyer lemons',
    longDescription: 'Meyer lemons — a cross between a lemon and mandarin — are sweeter and less acidic than regular lemons, with thin edible skin. Perfect for lemonade, curds, and baking.',
    rating: 4.8, reviews: 378, tag: 'Gourmet', nutritionHighlight: 'Vitamin C & Flavonoids', origin: 'Nagpur, Maharashtra', stock: 60,
    keywords: ['lemon', 'meyer lemon', 'citrus', 'sour', 'lemonade', 'baking', 'yellow'],
  },
  {
    id: 71, name: 'Navel Oranges', category: 'citrus', price: 79, originalPrice: 100, unit: '1 kg',
    emoji: '🍊', image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&q=80',
    bg: 'from-orange-100 to-yellow-50', accent: '#f97316', badge: null, badgeColor: '',
    description: 'Seedless, juicy Nagpur oranges — India\'s finest',
    longDescription: 'Sweet, seedless Nagpur navel oranges — famous across India for exceptional sweetness and easy peeling. Perfect for juicing, eating fresh, and making marmalade.',
    rating: 4.8, reviews: 1067, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Hesperidin', origin: 'Nagpur, Maharashtra', stock: 80,
    keywords: ['orange', 'nagpur', 'citrus', 'juice', 'sweet', 'seedless', 'vitamin C'],
  },
  {
    id: 72, name: 'Kaffir Lime', category: 'citrus', price: 59, originalPrice: 80, unit: '100g',
    emoji: '🍋', image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80',
    bg: 'from-lime-100 to-green-50', accent: '#65a30d', badge: 'AROMATIC', badgeColor: 'bg-lime-600',
    description: 'Knobbly lime with intensely aromatic zest',
    longDescription: 'Kaffir lime (makrut) with distinctive bumpy skin and incredibly aromatic zest. Essential in Thai and South-East Asian cooking. Adds unique citrusy depth to curries.',
    rating: 4.9, reviews: 178, tag: 'Imported', nutritionHighlight: 'Vitamin C & Limonene', origin: 'Thailand', stock: 25,
    keywords: ['lime', 'kaffir lime', 'thai', 'aromatic', 'zest', 'citrus', 'curry', 'makrut'],
  },
  {
    id: 73, name: 'Pink Grapefruit', category: 'citrus', price: 89, originalPrice: 115, unit: '2 pcs',
    emoji: '🍊', image: 'https://images.unsplash.com/photo-1529733827-9e3f47f5e6e0?w=600&q=80',
    bg: 'from-pink-100 to-orange-50', accent: '#f472b6', badge: null, badgeColor: '',
    description: 'Sweet pink grapefruit with low bitterness',
    longDescription: 'Pink-fleshed grapefruit sweeter and less bitter than white varieties. Rich in Vitamin C and lycopene. Great for breakfast, fresh juice, or cocktails.',
    rating: 4.7, reviews: 223, tag: 'Imported', nutritionHighlight: 'Vitamin C & Lycopene', origin: 'South Africa', stock: 30,
    keywords: ['grapefruit', 'pink', 'citrus', 'juice', 'breakfast', 'imported', 'sweet'],
  },
  {
    id: 74, name: 'Blood Oranges', category: 'citrus', price: 129, originalPrice: 169, unit: '500g',
    emoji: '🍊', image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&q=80',
    bg: 'from-red-100 to-orange-50', accent: '#dc2626', badge: 'RARE', badgeColor: 'bg-red-500',
    description: 'Deep ruby-fleshed blood oranges — dramatic & delicious',
    longDescription: 'Stunning blood oranges with deep burgundy flesh from Sicily and Spain. The anthocyanins responsible for the red colour add a unique berry-citrus flavour profile.',
    rating: 4.9, reviews: 134, tag: 'Imported', nutritionHighlight: 'Anthocyanins & Vitamin C', origin: 'Italy / Spain', stock: 18,
    keywords: ['blood orange', 'red', 'citrus', 'sicily', 'rare', 'imported', 'dramatic'],
  },
  {
    id: 75, name: 'Mandarin Clementines', category: 'citrus', price: 99, originalPrice: 130, unit: '500g',
    emoji: '🍊', image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&q=80',
    bg: 'from-orange-100 to-amber-50', accent: '#f97316', badge: null, badgeColor: '',
    description: 'Easy-peel clementines — the perfect snack',
    longDescription: 'Sweet, seedless clementines that practically peel themselves. Intensely sweet with a bright citrus flavour. Perfect pocket-sized snack for kids and adults alike.',
    rating: 4.8, reviews: 489, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Folate', origin: 'Nagpur / Coorg, Karnataka', stock: 50,
    keywords: ['clementine', 'mandarin', 'orange', 'easy peel', 'sweet', 'snack', 'kids'],
  },

  // ── EXOTIC (8) ──────────────────────────────────────────────────────────────
  {
    id: 76, name: 'Dragon Fruit', category: 'exotic', price: 189, originalPrice: 220, unit: '400g',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80',
    bg: 'from-pink-100 to-fuchsia-50', accent: '#ec4899', badge: 'EXOTIC', badgeColor: 'bg-pink-500',
    description: 'Vibrant pitaya — a visual showstopper',
    longDescription: 'Striking pink dragon fruit (pitaya) with crisp white flesh and tiny black seeds. Mild flavour with subtle sweetness. A showstopper for smoothie bowls and fruit platters.',
    rating: 4.8, reviews: 389, tag: 'Imported', nutritionHighlight: 'Vitamin C & Prebiotics', origin: 'Vietnam / Thailand', stock: 20,
    keywords: ['dragon fruit', 'pitaya', 'pink', 'exotic', 'smoothie bowl', 'tropical', 'striking'],
  },
  {
    id: 77, name: 'Avocado', category: 'exotic', price: 179, originalPrice: 230, unit: '2 pcs',
    emoji: '🥑', image: 'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=600&q=80',
    bg: 'from-green-100 to-emerald-50', accent: '#16a34a', badge: 'TRENDING', badgeColor: 'bg-green-600',
    description: 'Creamy Hass avocados — ripe & ready to eat',
    longDescription: 'Creamy, nutty Hass avocados selected at perfect ripeness. Rich in heart-healthy monounsaturated fats and 20+ vitamins. Make guacamole, avocado toast, or smoothies.',
    rating: 4.8, reviews: 845, tag: 'Imported', nutritionHighlight: 'Oleic Acid & Folate', origin: 'Mexico / India', stock: 25,
    keywords: ['avocado', 'hass', 'creamy', 'guacamole', 'toast', 'healthy fat', 'trending'],
  },
  {
    id: 78, name: 'Jackfruit', category: 'exotic', price: 99, originalPrice: 130, unit: '500g',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&q=80',
    bg: 'from-yellow-100 to-green-50', accent: '#ca8a04', badge: 'SEASONAL', badgeColor: 'bg-yellow-600',
    description: 'Sweet ripe jackfruit — India\'s largest fruit',
    longDescription: 'Fragrant, honey-sweet ripe jackfruit bulbs — India\'s national fruit. Each pod is succulent and incredibly sweet. Also popular as a vegan meat substitute when raw.',
    rating: 4.7, reviews: 467, tag: 'Local', nutritionHighlight: 'Vitamin B6 & Potassium', origin: 'Kerala / Karnataka', stock: 35,
    keywords: ['jackfruit', 'kathal', 'tropical', 'sweet', 'vegan', 'india', 'large', 'seasonal'],
  },
  {
    id: 79, name: 'Rambutan', category: 'exotic', price: 199, originalPrice: 260, unit: '250g',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1596591868231-05e808fd7b79?w=600&q=80',
    bg: 'from-red-50 to-pink-50', accent: '#f43f5e', badge: 'EXOTIC', badgeColor: 'bg-red-500',
    description: 'Hairy red fruit with lychee-like sweet flesh',
    longDescription: 'Exotic rambutan from Southeast Asian farms — translucent, jelly-like flesh with sweet, floral flavour similar to lychee. Visually dramatic spiky red exterior.',
    rating: 4.8, reviews: 167, tag: 'Imported', nutritionHighlight: 'Vitamin C & Copper', origin: 'Thailand / Malaysia', stock: 18,
    keywords: ['rambutan', 'exotic', 'red', 'tropical', 'imported', 'lychee', 'hairy', 'spiky'],
  },
  {
    id: 80, name: 'Medjool Dates', category: 'exotic', price: 249, originalPrice: 320, unit: '250g',
    emoji: '🍇', image: 'https://images.unsplash.com/photo-1593179357196-e11a93bf3f2e?w=600&q=80',
    bg: 'from-amber-100 to-orange-50', accent: '#b45309', badge: 'PREMIUM', badgeColor: 'bg-amber-700',
    description: 'Plump Medjool dates — nature\'s pure caramel',
    longDescription: 'Large, plump Medjool dates — each one is like eating caramel from nature. Incredibly rich, sweet, and satisfying. Great as natural sweetener in smoothies and energy balls.',
    rating: 4.9, reviews: 534, tag: 'Imported', nutritionHighlight: 'Iron, Potassium & Magnesium', origin: 'Saudi Arabia / Israel', stock: 30,
    keywords: ['dates', 'medjool', 'sweet', 'caramel', 'energy', 'natural sugar', 'healthy'],
  },
  {
    id: 81, name: 'Star Fruit', category: 'exotic', price: 149, originalPrice: 199, unit: '300g',
    emoji: '⭐', image: 'https://images.unsplash.com/photo-1617957689233-207e3cd3c610?w=600&q=80',
    bg: 'from-yellow-50 to-lime-50', accent: '#eab308', badge: 'EXOTIC', badgeColor: 'bg-yellow-500',
    description: 'Crisp carambola — naturally slices into stars',
    longDescription: 'Golden star fruit (carambola) with crispy, waxy texture and a unique sweet-tart flavour. Slices naturally form perfect stars — stunning edible garnish and conversation piece.',
    rating: 4.6, reviews: 145, tag: 'Imported', nutritionHighlight: 'Vitamin C & Fibre', origin: 'Malaysia / India', stock: 22,
    keywords: ['star fruit', 'carambola', 'star', 'tropical', 'exotic', 'yellow', 'garnish'],
  },
  {
    id: 82, name: 'Lychee', category: 'exotic', price: 149, originalPrice: 199, unit: '250g',
    emoji: '🍇', image: 'https://images.unsplash.com/photo-1596591868231-05e808fd7b79?w=600&q=80',
    bg: 'from-pink-100 to-rose-50', accent: '#fb7185', badge: 'SEASONAL', badgeColor: 'bg-pink-500',
    description: 'Fragrant summer lychees with sweet floral flesh',
    longDescription: 'Fragrant Muzaffarpur lychees — India\'s most prized variety. Beneath the red shell lies translucent, juicy flesh with an intensely sweet, floral flavour reminiscent of roses.',
    rating: 5.0, reviews: 712, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Oligonol', origin: 'Bihar / West Bengal', stock: 20,
    keywords: ['lychee', 'litchi', 'pink', 'seasonal', 'sweet', 'floral', 'summer', 'muzaffarpur'],
  },
  {
    id: 83, name: 'Fresh Figs', category: 'exotic', price: 199, originalPrice: 260, unit: '250g',
    emoji: '🍈', image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80',
    bg: 'from-purple-100 to-pink-50', accent: '#a855f7', badge: 'SEASONAL', badgeColor: 'bg-purple-500',
    description: 'Luscious black figs with honeyed interior',
    longDescription: 'Rare fresh Black Mission figs with deep purple skin and honey-sweet, jam-like interior. Available for a very brief season. Eat with brie and honey, or stuff with gorgonzola.',
    rating: 4.9, reviews: 167, tag: 'Seasonal', nutritionHighlight: 'Prebiotic Fibre & Calcium', origin: 'Maharashtra', stock: 12,
    keywords: ['fig', 'anjeer', 'purple', 'honey', 'seasonal', 'gourmet', 'rare', 'brie'],
  },

  // ── SEASONAL (5) ────────────────────────────────────────────────────────────
  {
    id: 84, name: 'Himachali Cherries', category: 'seasonal', price: 299, originalPrice: 380, unit: '250g',
    emoji: '🍒', image: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#dc2626', badge: 'LIMITED', badgeColor: 'bg-red-600',
    description: 'Deep red sweet cherries — available for 4 weeks only',
    longDescription: 'Deep red sweet cherries from Kinnaur\'s high-altitude orchards. Available for only 4–6 weeks each year. Rich in melatonin — a natural sleep aid fruit.',
    rating: 5.0, reviews: 478, tag: 'Seasonal', nutritionHighlight: 'Melatonin & Anthocyanins', origin: 'Kinnaur, HP', stock: 12,
    keywords: ['cherry', 'cherries', 'red', 'seasonal', 'sweet', 'himachal', 'kinnaur', 'limited'],
  },
  {
    id: 85, name: 'Winter Strawberries', category: 'seasonal', price: 149, originalPrice: 199, unit: '500g',
    emoji: '🍓', image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&q=80',
    bg: 'from-rose-100 to-pink-50', accent: '#f43f5e', badge: 'SEASONAL', badgeColor: 'bg-rose-500',
    description: 'Large winter strawberries — sweeter in the cold',
    longDescription: 'Winter Mahabaleshwar strawberries are larger and sweeter than summer varieties — the cold stress produces more natural sugars. Don\'t miss this brief window.',
    rating: 4.9, reviews: 312, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Folate', origin: 'Mahabaleshwar, MH', stock: 25,
    keywords: ['strawberry', 'winter', 'seasonal', 'sweet', 'large', 'mahabaleshwar', 'cold'],
  },
  {
    id: 86, name: 'Tender Coconut', category: 'seasonal', price: 55, originalPrice: 72, unit: '1 pc',
    emoji: '🥥', image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&q=80',
    bg: 'from-green-50 to-teal-50', accent: '#0d9488', badge: 'SUMMER', badgeColor: 'bg-teal-500',
    description: 'Young green tender coconut — chilled & ready',
    longDescription: 'Young green coconuts full of refreshing electrolyte-rich water. Served chilled, pre-chilled, with a straw. The best summer thirst-quencher. Soft, jelly-like malai inside.',
    rating: 4.9, reviews: 689, tag: 'Summer', nutritionHighlight: 'Electrolytes & Coconut Water', origin: 'Kerala', stock: 40,
    keywords: ['tender coconut', 'green coconut', 'coconut water', 'summer', 'chilled', 'malai'],
  },
  {
    id: 87, name: 'Alphonso Slice Pack', category: 'seasonal', price: 149, originalPrice: 199, unit: '200g',
    emoji: '🥭', image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80',
    bg: 'from-yellow-100 to-amber-50', accent: '#f59e0b', badge: 'SEASONAL', badgeColor: 'bg-amber-500',
    description: 'Pre-cut Alphonso mango slices — ready to eat',
    longDescription: 'Freshly cut Alphonso mango slices packed hygienically for instant enjoyment. No mess, no hassle. Pure mango joy in under 60 seconds. Perfect office snack.',
    rating: 4.9, reviews: 567, tag: 'Premium', nutritionHighlight: 'Vitamin C & Beta-carotene', origin: 'Ratnagiri, Maharashtra', stock: 30,
    keywords: ['mango slices', 'alphonso', 'cut mango', 'ready to eat', 'seasonal', 'snack'],
  },
  {
    id: 88, name: 'Raw Mango', category: 'seasonal', price: 79, originalPrice: 105, unit: '500g',
    emoji: '🥭', image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80',
    bg: 'from-green-100 to-lime-50', accent: '#65a30d', badge: 'SEASONAL', badgeColor: 'bg-green-600',
    description: 'Tangy raw mango for pickles, aam panna & chutney',
    longDescription: 'Firm, tart raw mangoes (kachchi kairi) — perfect for making aam panna, raw mango chutney, mango pickle (achar), and adding sourness to dals.',
    rating: 4.8, reviews: 389, tag: 'Seasonal', nutritionHighlight: 'Vitamin C & Pectin', origin: 'Maharashtra / AP', stock: 35,
    keywords: ['raw mango', 'kachchi kairi', 'tangy', 'pickle', 'aam panna', 'chutney', 'sour'],
  },

  // ── ROOT VEGETABLES (12) ─────────────────────────────────────────────────────
  {
    id: 89, name: 'Orange Carrots', category: 'root', price: 35, originalPrice: 48, unit: '500g',
    emoji: '🥕', image: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?w=600&q=80',
    bg: 'from-orange-100 to-amber-50', accent: '#f97316', badge: 'BESTSELLER', badgeColor: 'bg-orange-500',
    description: 'Sweet, crunchy carrots straight from the farm',
    longDescription: 'Freshly pulled orange carrots with intense sweetness and vibrant colour. Rich in beta-carotene which converts to Vitamin A. Perfect for juicing, salads, and cooking.',
    rating: 4.8, reviews: 1241, tag: 'Organic', nutritionHighlight: 'Beta-carotene & Vitamin A', origin: 'Ooty, Tamil Nadu', stock: 90,
    keywords: ['carrot', 'gajar', 'orange', 'juice', 'salad', 'sweet', 'organic', 'vitamin A'],
  },
  {
    id: 90, name: 'Red Beetroot', category: 'root', price: 49, originalPrice: 65, unit: '500g',
    emoji: '🍠', image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&q=80',
    bg: 'from-red-100 to-rose-50', accent: '#dc2626', badge: null, badgeColor: '',
    description: 'Earthy, sweet beetroot — perfect for juicing',
    longDescription: 'Deep ruby-red beetroot bursting with earthy sweetness. A superfood for cardiovascular health and liver function. Great roasted, pickled, or as fresh juice.',
    rating: 4.7, reviews: 498, tag: 'Organic', nutritionHighlight: 'Nitrates, Folate & Iron', origin: 'Nashik, Maharashtra', stock: 60,
    keywords: ['beetroot', 'beet', 'red', 'juice', 'detox', 'roast', 'purple', 'stamina'],
  },
  {
    id: 91, name: 'Baby Potatoes', category: 'root', price: 55, originalPrice: 70, unit: '500g',
    emoji: '🥔', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80',
    bg: 'from-yellow-50 to-amber-50', accent: '#d97706', badge: 'BESTSELLER', badgeColor: 'bg-amber-500',
    description: 'Tender baby potatoes — perfect for roasting',
    longDescription: 'Small, creamy baby potatoes with thin skins that crisp up beautifully when roasted. No peeling needed. Perfect boiled whole, roasted with herbs, or in potato salads.',
    rating: 4.8, reviews: 1056, tag: 'Local', nutritionHighlight: 'Potassium & Vitamin B6', origin: 'Shimla, HP', stock: 100,
    keywords: ['potato', 'baby potato', 'roast', 'boil', 'aloo', 'small', 'creamy', 'shimla'],
  },
  {
    id: 92, name: 'Sweet Potato', category: 'root', price: 55, originalPrice: 72, unit: '500g',
    emoji: '🍠', image: 'https://images.unsplash.com/photo-1596097635121-14b38c5d7a27?w=600&q=80',
    bg: 'from-orange-100 to-yellow-50', accent: '#f59e0b', badge: null, badgeColor: '',
    description: 'Naturally sweet orange flesh — great for baking',
    longDescription: 'Rich, orange-fleshed sweet potatoes with natural caramel sweetness. Bake, mash, fry, or use in smoothies. A nutrient powerhouse. Popular with runners for energy.',
    rating: 4.7, reviews: 623, tag: 'Organic', nutritionHighlight: 'Beta-carotene & Fibre', origin: 'Odisha', stock: 75,
    keywords: ['sweet potato', 'shakarkandi', 'orange', 'bake', 'mash', 'healthy', 'energy'],
  },
  {
    id: 93, name: 'White Radish (Daikon)', category: 'root', price: 25, originalPrice: 35, unit: '500g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-gray-50 to-white', accent: '#9ca3af', badge: null, badgeColor: '',
    description: 'Crisp, mild daikon for salads & pickles',
    longDescription: 'Long white daikon radish with mild, slightly peppery flavour. Excellent raw in salads, pickled in vinegar, or cooked in soups. Perfect for Korean kimchi.',
    rating: 4.5, reviews: 312, tag: 'Fresh', nutritionHighlight: 'Vitamin C & Digestive Enzymes', origin: 'Punjab', stock: 80,
    keywords: ['radish', 'mooli', 'daikon', 'white', 'pickle', 'salad', 'korean', 'kimchi'],
  },
  {
    id: 94, name: 'Turnip', category: 'root', price: 39, originalPrice: 52, unit: '500g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-purple-50 to-white', accent: '#a855f7', badge: null, badgeColor: '',
    description: 'Earthy, mild turnips — great for winter soups',
    longDescription: 'Tender young turnips with mild, slightly sweet flavour. Excellent roasted until caramelised, mashed with butter, or added to hearty winter stews.',
    rating: 4.5, reviews: 178, tag: 'Winter', nutritionHighlight: 'Glucosinolates & Vitamin C', origin: 'Punjab / HP', stock: 45,
    keywords: ['turnip', 'shalgam', 'root vegetable', 'winter', 'soup', 'roast', 'mild'],
  },
  {
    id: 95, name: 'Taro Root (Arbi)', category: 'root', price: 45, originalPrice: 60, unit: '500g',
    emoji: '🍠', image: 'https://images.unsplash.com/photo-1596097635121-14b38c5d7a27?w=600&q=80',
    bg: 'from-stone-100 to-gray-50', accent: '#78716c', badge: null, badgeColor: '',
    description: 'Starchy taro root — comfort food across cuisines',
    longDescription: 'Starchy taro root (arbi) with slippery texture that becomes silky when cooked correctly. Excellent boiled and tempered with mustard seeds, or fried into crispy taro chips.',
    rating: 4.6, reviews: 234, tag: 'Local', nutritionHighlight: 'Resistant Starch & Potassium', origin: 'Maharashtra / UP', stock: 55,
    keywords: ['taro', 'arbi', 'root', 'starchy', 'fried', 'chips', 'asian', 'curry'],
  },
  {
    id: 96, name: 'Purple Yam', category: 'root', price: 69, originalPrice: 90, unit: '500g',
    emoji: '🍠', image: 'https://images.unsplash.com/photo-1596097635121-14b38c5d7a27?w=600&q=80',
    bg: 'from-purple-100 to-violet-50', accent: '#7c3aed', badge: 'EXOTIC', badgeColor: 'bg-purple-500',
    description: 'Vibrant purple yam with stunning colour',
    longDescription: 'Stunning purple yam (ratalu/ube) with brilliant violet flesh. Used in Filipino desserts (ube halaya), ice cream, and curries. The colour comes from anthocyanin antioxidants.',
    rating: 4.7, reviews: 156, tag: 'Exotic', nutritionHighlight: 'Anthocyanins & Potassium', origin: 'Konkan, Maharashtra', stock: 25,
    keywords: ['purple yam', 'ratalu', 'ube', 'violet', 'purple', 'exotic', 'dessert'],
  },
  {
    id: 97, name: 'Lotus Root', category: 'root', price: 99, originalPrice: 130, unit: '300g',
    emoji: '🌸', image: 'https://images.unsplash.com/photo-1553182698-6aff7d7b2696?w=600&q=80',
    bg: 'from-pink-50 to-rose-50', accent: '#fb7185', badge: 'EXOTIC', badgeColor: 'bg-rose-500',
    description: 'Crunchy lotus root with beautiful lace pattern',
    longDescription: 'Fresh lotus root (kamal kakdi) with striking lace-like cross-section. Crunchy, mildly sweet, and starchy. Beautiful in stir-fries and tempura. Also used in curries.',
    rating: 4.8, reviews: 156, tag: 'Exotic', nutritionHighlight: 'Vitamin C & Iron', origin: 'Bihar / Rajasthan', stock: 20,
    keywords: ['lotus root', 'kamal kakdi', 'lace', 'crunchy', 'exotic', 'stir fry', 'tempura'],
  },
  {
    id: 98, name: 'Celery Stalks', category: 'root', price: 59, originalPrice: 80, unit: '1 bunch',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&q=80',
    bg: 'from-green-50 to-lime-50', accent: '#65a30d', badge: null, badgeColor: '',
    description: 'Crunchy celery for snacking, juicing & cooking',
    longDescription: 'Fresh, crisp celery stalks with their characteristic clean, slightly salty flavour. Eat raw with peanut butter, use as mirepoix base, or juice for alkalising properties.',
    rating: 4.5, reviews: 245, tag: 'Fresh', nutritionHighlight: 'Apigenin & Vitamin K', origin: 'Maharashtra', stock: 45,
    keywords: ['celery', 'stalk', 'crunch', 'juice', 'snack', 'green', 'mirepoix'],
  },
  {
    id: 99, name: 'Fennel Bulb', category: 'root', price: 79, originalPrice: 105, unit: '2 pcs',
    emoji: '🌿', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-green-50 to-teal-50', accent: '#0d9488', badge: 'GOURMET', badgeColor: 'bg-teal-500',
    description: 'Crisp anise-flavoured fennel — Mediterranean gem',
    longDescription: 'Crisp white fennel bulbs with distinctive mild anise flavour. Excellent raw in salads, braised until sweet and tender, or roasted alongside fish. Feathery fronds make beautiful garnish.',
    rating: 4.7, reviews: 156, tag: 'Gourmet', nutritionHighlight: 'Anethole & Vitamin C', origin: 'Rajasthan', stock: 25,
    keywords: ['fennel', 'anise', 'mediterranean', 'gourmet', 'crisp', 'white', 'fish', 'italian'],
  },
  {
    id: 100, name: 'Jerusalem Artichoke', category: 'root', price: 89, originalPrice: 120, unit: '300g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80',
    bg: 'from-stone-100 to-amber-50', accent: '#92400e', badge: 'RARE', badgeColor: 'bg-stone-600',
    description: 'Sunchoke — nutty, sweet flavour when roasted',
    longDescription: 'Jerusalem artichoke (sunchoke) — a knobbly tuber with a sweet, nutty flavour that becomes caramel-like when roasted. Also excellent in soups and salads.',
    rating: 4.7, reviews: 89, tag: 'Rare', nutritionHighlight: 'Inulin (Prebiotic) & Iron', origin: 'Maharashtra', stock: 15,
    keywords: ['jerusalem artichoke', 'sunchoke', 'knobbly', 'nutty', 'sweet', 'roast', 'rare'],
  },
  {
    id: 101, name: 'Purple Carrot', category: 'root', price: 65, originalPrice: 88, unit: '400g',
    emoji: '🥕', image: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?w=600&q=80',
    bg: 'from-purple-100 to-indigo-50', accent: '#7c3aed', badge: 'HEIRLOOM', badgeColor: 'bg-purple-600',
    description: 'Heirloom purple carrots — sweeter & nuttier',
    longDescription: 'Ancient purple-skinned carrots with orange or yellow interior — the original carrots before selective breeding made them all orange. Sweeter and nuttier with more antioxidants.',
    rating: 4.8, reviews: 134, tag: 'Heirloom', nutritionHighlight: 'Anthocyanins & Beta-carotene', origin: 'Rajasthan / UP', stock: 20,
    keywords: ['purple carrot', 'heirloom', 'antioxidant', 'ancient', 'sweet', 'carrot', 'colorful'],
  },
  {
    id: 102, name: 'Parsnip', category: 'root', price: 89, originalPrice: 120, unit: '500g',
    emoji: '🌱', image: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=600&q=80',
    bg: 'from-amber-50 to-yellow-50', accent: '#d97706', badge: null, badgeColor: '',
    description: 'Sweet, nutty parsnip — stunning when roasted',
    longDescription: 'Ivory-coloured parsnip with a sweet, earthy, nutty flavour that intensifies with roasting or caramelising. A Christmas dinner classic in Europe, now available fresh in India.',
    rating: 4.7, reviews: 78, tag: 'Imported', nutritionHighlight: 'Folate & Vitamin C', origin: 'Himachal Pradesh', stock: 20,
    keywords: ['parsnip', 'white', 'root', 'roast', 'nutty', 'sweet', 'european', 'christmas'],
  },
]

// ── AI-READY HELPERS ────────────────────────────────────────────────────────
export const productsByKeyword = (keyword: string): Product[] => {
  const lower = keyword.toLowerCase()
  return products.filter(p =>
    p.keywords.some(k => k.includes(lower)) ||
    p.name.toLowerCase().includes(lower) ||
    p.category.toLowerCase().includes(lower) ||
    p.description.toLowerCase().includes(lower) ||
    p.origin.toLowerCase().includes(lower)
  )
}

export const productsByCategory = (cat: string): Product[] =>
  cat === 'all' ? products : products.filter(p => p.category === cat)

export const productsByPriceRange = (min: number, max: number): Product[] =>
  products.filter(p => p.price >= min && p.price <= max)

export const featuredProducts = products.filter(p => p.badge !== null).slice(0, 12)

export const getProductCatalogForAI = (): string =>
  products.map(p =>
    `${p.name} | ${p.category} | ₹${p.price}/${p.unit} | ${p.tag} | ${p.origin} | ${p.keywords.join(', ')}`
  ).join('\n')

// Testimonials, Stats, Marquee
export const testimonials = [
  { id:1, name:'Priya Sharma',  location:'Noida, UP',    avatar:'👩',    text:'VegFru has completely transformed my kitchen. The freshness is unreal — I received spinach that was still dewy from harvest!', rating:5, verified:true },
  { id:2, name:'Rahul Mehta',   location:'Gurugram',      avatar:'👨',    text:'Their seasonal boxes are incredible value and introduce me to vegetables I never knew existed.', rating:5, verified:true },
  { id:3, name:'Ananya Reddy',  location:'Delhi',         avatar:'👩‍🦱', text:"The Alphonso mangoes were the best I've ever had. My parents said it reminded them of childhood summers in Konkan.", rating:5, verified:true },
  { id:4, name:'Karan Patel',   location:'Faridabad, HR', avatar:'🧑',    text:'The delivery speed is amazing. Order at 8 AM, fresh veggies by noon. The mushrooms and asparagus are genuinely restaurant-quality.', rating:5, verified:true },
]

export const stats = [
  { value:'12,400+', label:'Happy Families',   emoji:'🏠' },
  { value:'102+',    label:'Products Daily',   emoji:'🌾' },
  { value:'4–6hrs',  label:'Farm to Door',     emoji:'⚡' },
  { value:'98%',     label:'Satisfaction Rate',emoji:'❤️' },
]

export const marqueeItems = [
  '🍅 Cherry Tomatoes', '🥭 Alphonso Mangoes', '🫐 Blueberries',
  '🥬 Baby Spinach', '🌶️ Kashmiri Chillies', '🍋 Meyer Lemons',
  '🧅 Shallots', '🍇 Nashik Grapes', '🫛 Green Peas',
  '🍍 Kew Pineapple', '🌽 Sweet Corn', '🥑 Hass Avocados',
  '🍓 Mahabaleshwar Strawberries', '🥦 Purple Broccoli', '🥕 Baby Carrots',
  '🍊 Nagpur Oranges', '🍒 Kinnaur Cherries', '🌿 Microgreens',
  '🥝 NZ Kiwis', '🍈 Dragon Fruit', '🌱 Moringa Drumstick',
]
